services:
  netconf-mock:
    build:
      context: docker/netconf-mock
      dockerfile: Dockerfile
    container_name: netconf-mock
    ports:
      - "830:830"
      - "8088:8088"
    environment:
      - NETCONF_USER=admin
      - NETCONF_PASSWORD=admin
